/vis/open OGL
/vis/drawVolume
/vis/viewer/set/style wireframe 
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointVector 1 0 0
/tracking/storeTrajectory 1
/vis/scene/add/axes 1 1 1 10 cm
/vis/scene/add/trajectories
/tracking/storeTrajectory 1
#/process/optical/verbose 2
/vis/modeling/trajectories/create/drawByParticleID
/vis/scene/endOfEventAction accumulate
/vis/viewer/set/autoRefresh true
/run/beamOn 10

