/vis/open OGL
/vis/drawVolume
/vis/viewer/set/style wireframe 
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointVector 1 0 0
/tracking/storeTrajectory 1
/vis/scene/add/axes 0 7.75 0 100 mm
/vis/scene/add/trajectories
/tracking/storeTrajectory 1
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default white   
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton red
/vis/modeling/trajectories/create/drawByParticleID
/vis/scene/endOfEventAction accumulate
/vis/viewer/set/autoRefresh true
/run/beamOn 100
/vis/viewer/flush
